module_name: "example_dam"


buckets:
    bucket_1:
        id: 1
        frequency_hz: 50
        parameters:
            - dam_chan_1
            - dam_chan_2
            - dam_chan_3
            
    bucket_2:
        id: 2
        frequency_hz: 10
        parameters:
            - dam_chan_4
            - dam_chan_5
            - dam_chan_6
            - u16_tester


parameters_produced:
# ADC1:
    dam_chan_1:
        produced_by: ADC1_IN0
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 100
        
    dam_chan_2:
        produced_by: ADC1_IN1
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10       

# ADC2:
    dam_chan_3:
        produced_by: ADC2_IN2
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 100
        
    dam_chan_4:
        produced_by: ADC2_IN3
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
            
# ADC3:
    dam_chan_5:
        produced_by: ADC3_IN4
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 100
        
    dam_chan_6:
        produced_by: ADC3_IN5
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        
