module_name: "example_dam"


buckets:
    bucket_1:
        id: 1
        frequency_hz: 50
        parameters:
            - dam_chan_1
            - dam_chan_2
            - dam_chan_3
            
    bucket_2:
        id: 2
        frequency_hz: 10
        parameters:
            - dam_chan_4
            - dam_chan_5
            - dam_chan_6

    bucket_3:
        id: 3
        frequency_hz: 1
        parameters:
            - float_tester_4
            - float_tester_5
            - float_tester_6
            - example_new_param

parameters_produced:
# ADC1:
    dam_chan_1:
        produced_by: ADC1_IN0
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 100
        
    dam_chan_2:
        produced_by: ADC1_IN1
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10       

# ADC2:
    dam_chan_3:
        produced_by: ADC2_IN2
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 100
        
    dam_chan_4:
        produced_by: ADC2_IN3
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
            
# ADC3:
    dam_chan_5:
        produced_by: ADC3_IN4
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 100
        
    dam_chan_6:
        produced_by: ADC3_IN5
        sensor:
            name: "test_voltage_sensor"
            output: voltage
        num_samples_buffered: 10
        

# CAN sensors:
    float_tester_4:
        produced_by: CAN
        sensor:
            name: "test_can_sensor"
            output: d16_fixed
        num_samples_buffered: 1
            
    float_tester_5:
        produced_by: CAN
        sensor:
            name: "test_can_sensor"
            output: u16_raw
        num_samples_buffered: 1
            
    float_tester_6:
        produced_by: CAN
        sensor:
            name: "test_can_sensor"
            output: float_1_raw
        num_samples_buffered: 1
            
    example_new_param:
        produced_by: CAN
        sensor:
            name: "test_can_sensor"
            output: float_2_scaled
        num_samples_buffered: 1

