module_name: "TCM_with_ECU_Decoding"


buckets:
    high_frequency_ecu:
        id: 1
        frequency_hz: 200
        parameters:
            - rpm_ecu
            - wheel_slip_ecu
            - wheel_slip_target_ecu
            - aim_rpm_ecu
            - wsfl_ecu
            - wsfr_ecu
            - wsrl_ecu
            - wsrr_ecu
            - ign_cut_level_ecu
            
    low_frequency_ecu:
        id: 2
        frequency_hz: 20
        parameters:
            - bat_volts_ecu
            - engine_temp_ecu
            - inlet_air_temp_ecu
            - lambda_1_ecu
            - throttle_pos_1_ecu
            - throttle_pos_2_ecu
            - pedal_pos_1_ecu
            - pedal_pos_2_ecu
            - man_pressure_ecu
            - fuel_cut_lvl_ecu
            - ign_advance_ecu
            - oil_pressure_ecu
            - oil_temp_ecu
            - fuel_pressure_ecu
            - throttle_pos_required_ecu
            - brake_pressure_front_ecu
            - etc_duty_ecu
            - fan_duty_ecu
            - fanoil_duty_ecu
            - wpump_duty_ecu
            - brake_light_duty_ecu
            - warning_light_duty_ecu
            - aux_5v_ecu
            - eng_5v_ecu
            - gps_lat_ecu
            - gps_long_ecu
            
    high_frequency_tcm:
        id: 3
        frequency_hz: 250
        parameters:
            - rear_left_shock_pot
            - rear_right_shock_pot
            
            
    low_frequency_tcm:
        id: 4
        frequency_hz: 100
        parameters:
            - sw_upshift
            - sw_downshift
            - sw_clutch_fast
            - sw_clutch_slow
            - sw_aero_front
            - sw_aero_rear
            - tcm_neutral
            - tcm_target_rpm
            - tcm_current_gear
            - tcm_target_gear
            - tcm_currently_moving
            - tcm_successful_shift
            - tcm_shifter_position
            - tcm_clutch_position
            - tcm_trans_rpm
            - tcm_throttle_blip
            - tcm_using_clutch
            - tcm_anti_stall
            - tcm_lap_timer

parameters_produced:
# Analog sensors
    tcm_shifter_position:
        produced_by: ADC2_IN11
        sensor:
            name: linear_pos_sensor_50
            output: voltage
        num_samples_buffered: 1
        
    tcm_clutch_position:
        produced_by: ADC1_IN10
        sensor:
            name: linear_pos_sensor_50
            output: voltage
        num_samples_buffered: 1
        
    rear_left_shock_pot:
        produced_by: ADC1_IN2
        sensor:
            name: linear_pos_sensor_25
            output: voltage
        num_samples_buffered: 1
        
    rear_right_shock_pot:
        produced_by: ADC1_IN3
        sensor:
            name: linear_pos_sensor_25
            output: voltage
        num_samples_buffered: 1

# CAN sensors:
# High frequency
    rpm_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_fast"
            output: rpm
        num_samples_buffered: 1
            
    wheel_slip_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_fast"
            output: wheel_slip
        num_samples_buffered: 1
        
    wheel_slip_target_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_fast"
            output: wheel_slip_target
        num_samples_buffered: 1
        
    aim_rpm_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_fast"
            output: aim_rpm
        num_samples_buffered: 1
        
    wsfl_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_fast"
            output: wsfl
        num_samples_buffered: 1
        
    wsfr_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_fast"
            output: wsfr
        num_samples_buffered: 1
        
    wsrl_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_fast"
            output: wsrl
        num_samples_buffered: 1
       
    wsrr_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_fast"
            output: wsrr
        num_samples_buffered: 1
        
    ign_cut_level_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_fast"
            output: ign_cut_level
        num_samples_buffered: 1
        
# low frequency
    bat_volts_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_slow"
            output: bat_volts
        num_samples_buffered: 1
        
    engine_temp_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_slow"
            output: engine_temp
        num_samples_buffered: 1
        
    inlet_air_temp_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_slow"
            output: inlet_air_temp
        num_samples_buffered: 1
        
    lambda_1_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_slow"
            output: lambda_1
        num_samples_buffered: 1
        
    throttle_pos_1_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_slow"
            output: throttle_pos_1
        num_samples_buffered: 1
        
    throttle_pos_2_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_slow"
            output: throttle_pos_2
        num_samples_buffered: 1
        
    pedal_pos_1_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_slow"
            output: pedal_pos_1
        num_samples_buffered: 1
        
    pedal_pos_2_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_slow"
            output: pedal_pos_2
        num_samples_buffered: 1
       
    man_pressure_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_slow"
            output: man_pressure
        num_samples_buffered: 1
        
    fuel_cut_lvl_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_slow"
            output: fuel_cut_level
        num_samples_buffered: 1
        
    ign_advance_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_slow"
            output: ign_advance
        num_samples_buffered: 1
        
    oil_pressure_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_slow"
            output: oil_pressure
        num_samples_buffered: 1
        
    oil_temp_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_slow"
            output: oil_temp
        num_samples_buffered: 1
        
    fuel_pressure_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_slow"
            output: fuel_pressure
        num_samples_buffered: 1
        
    throttle_pos_required_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_slow"
            output: throttle_pos_required
        num_samples_buffered: 1
        
    brake_pressure_front_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_slow"
            output: brake_pressure_front
        num_samples_buffered: 1
        
    etc_duty_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_slow"
            output: etc_duty
        num_samples_buffered: 1
        
    fan_duty_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_slow"
            output: fan_duty
        num_samples_buffered: 1
       
    fanoil_duty_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_slow"
            output: fanoil_duty
        num_samples_buffered: 1
        
    wpump_duty_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_slow"
            output: wpump_duty
        num_samples_buffered: 1
        
    brake_light_duty_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_slow"
            output: brake_light_duty
        num_samples_buffered: 1
       
    warning_light_duty_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_slow"
            output: warning_light_duty
        num_samples_buffered: 1
        
    aux_5v_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_slow"
            output: aux_5v
        num_samples_buffered: 1
        
    eng_5v_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_slow"
            output: eng_5v
        num_samples_buffered: 1
        
    gps_lat_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_slow"
            output: gps_lat
        num_samples_buffered: 1
        
    gps_long_ecu:
        produced_by: CAN
        sensor:
            name: "M600_ecu_slow"
            output: gps_long
        num_samples_buffered: 1
