
module_name: "example_sensor_hub"

buckets:
    bucket_0:
        # NOTE: frequency will be converted to an integer number of ms for a delay
        frequency_hz: 250
        parameters:
            # these must directly be a variable defined in GopherCAN
            dam_chan_1:
                ADC: ADC1_IN15
                sensor: linear_pos_sensor_50
                samples_buffered: 2
                
            dam_chan_2:
                ADC: ADC1_IN14
                sensor: linear_pos_sensor_50
                samples_buffered: 2
                
            dam_chan_3:
                ADC: ADC1_IN7
                sensor: linear_pos_sensor_50
                samples_buffered: 2

    bucket_1:
        frequency_hz: 1000
        parameters:
            dam_chan_4:
                ADC: ADC2_IN6
                sensor: linear_pos_sensor_50
                samples_buffered: 2
                
            dam_chan_5:
                ADC: ADC2_IN5
                sensor: linear_pos_sensor_50
                samples_buffered: 2
                
            dam_chan_6:
                ADC: ADC2_IN4
                sensor: linear_pos_sensor_50
                samples_buffered: 2
                
    bucket_2:
        frequency_hz: 50
        parameters:
            dam_chan_7:
                ADC: ADC3_IN3
                sensor: linear_pos_sensor_50
                samples_buffered: 2
                
            dam_chan_8:
                ADC: ADC3_IN2
                sensor: linear_pos_sensor_50
                samples_buffered: 2
                
            dam_chan_9:
                ADC: ADC3_IN1
                sensor: linear_pos_sensor_50
                samples_buffered: 2
                
            dam_chan_10:
                ADC: ADC3_IN0
                sensor: linear_pos_sensor_50
                samples_buffered: 2
